# Script to generate LUIE_MEDIA path constants for all files in LuiExtended\media

$mediaPath = "LuiMedia\media"
$outputFile = "LuiMedia\MediaPaths.lua"

if (-not (Test-Path $mediaPath)) {
    Write-Host "Error: Media path not found: $mediaPath" -ForegroundColor Red
    exit 1
}

Write-Host "Scanning media folder: $mediaPath" -ForegroundColor Cyan

# Get all files recursively, filter to only .dds and .slug files
$files = Get-ChildItem -Path $mediaPath -Recurse -File | Where-Object { $_.Extension -in @('.dds', '.slug') } | Sort-Object FullName

Write-Host "Found $($files.Count) files (.dds and .slug only)" -ForegroundColor Cyan

# Start building the Lua file content
$luaContent = @"
-- -----------------------------------------------------------------------------
--  LuiExtended Media Paths
--  Auto-generated by generate_media_paths.ps1
--  Distributed under The MIT License (MIT) (see LICENSE file)
-- -----------------------------------------------------------------------------

-- Base media path constant
LUIE_MEDIA = "LuiMedia/media"

-- Individual file path constants
"@

# Function to convert file path to valid Lua constant name
function ConvertToConstantName {
    param([string]$relativePath)
    
    # Normalize path separators
    $path = $relativePath -replace "\\", "_"
    $path = $path -replace "/", "_"
    $path = $path -replace "\.", "_"
    $path = $path -replace "-", "_"
    $path = $path -replace " ", "_"
    
    # Convert to uppercase and add prefix
    $constant = "LUIE_MEDIA_" + $path.ToUpper()
    
    # Remove trailing underscores from extension
    $constant = $constant -replace "_+$", ""
    
    return $constant
}

# Generate constants for each file
$constants = @{}
$mediaPathResolved = (Resolve-Path $mediaPath).Path
foreach ($file in $files) {
    # Get relative path from media folder
    $relativePath = $file.FullName -replace [regex]::Escape($mediaPathResolved + "\"), ""
    $relativePath = $relativePath -replace "\\", "/"
    $fullPath = "LuiMedia/media/" + $relativePath
    
    $constantName = ConvertToConstantName $relativePath
    
    # Handle duplicate constant names (shouldn't happen, but just in case)
    $counter = 1
    $originalName = $constantName
    while ($constants.ContainsKey($constantName)) {
        $constantName = $originalName + "_" + $counter
        $counter++
    }
    
    $constants[$constantName] = $fullPath
}

# Write constants to Lua file, sorted by name
$sortedConstants = $constants.GetEnumerator() | Sort-Object Name

foreach ($entry in $sortedConstants) {
    $luaContent += "`n$($entry.Key) = `"$($entry.Value)`""
}

# Write to file
$luaContent | Out-File -FilePath $outputFile -Encoding UTF8 -NoNewline

Write-Host "Generated $($constants.Count) constants in: $outputFile" -ForegroundColor Green
Write-Host "Done!" -ForegroundColor Green

