-- ////// START : GENERATED FROM C:/Users/dack_janiels/source/repos/LUIE/LuiExtended/LuiExtended/frontend\SpellCastBuffs.xml
---------- LVL: 00 ----------
---------- LVL: 01 ----------
---------- LVL: 02 ----------
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_PlayerBuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_PlayerDebuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_TargetBuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_TargetDebuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_ProminentBuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffs : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_ProminentDebuffs = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLong : TopLevelWindow
---@field public clampedToScreen boolean
---@field public mouseEnabled boolean
---@field public movable boolean
---@field public hidden boolean
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public level integer
---@field public space Space
---@field public OnMoveStart fun(self: Control)
---@field public OnMoveStop fun(self: Control)
LUIE_SpellCastBuffs_PlayerLong = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIcon : BackdropControl
---@field public mouseEnabled boolean
---@field public centerColor string
---@field public edgeColor string
---@field public space Space
---@field public OnMouseEnter fun(self: Control)
---@field public OnMouseExit fun(self: Control)
---@field public OnMouseUp fun(self: Control, button: integer, upInside: boolean, ctrl: boolean, alt: boolean, shift: boolean, command: boolean)
LUIE_SpellCastBuffIcon = {}
---------- LVL: 03 ----------
---------- LVL: 04 ----------
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerBuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerDebuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_TargetBuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_TargetDebuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_ProminentBuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsIconHolder : Control
---@field public space Space
LUIE_SpellCastBuffs_ProminentBuffsIconHolder = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_ProminentDebuffsPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsIconHolder : Control
---@field public space Space
LUIE_SpellCastBuffs_ProminentDebuffsIconHolder = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongPreview : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerLongPreview = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongIconHolder : Control
---@field public space Space
LUIE_SpellCastBuffs_PlayerLongIconHolder = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconBack : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffIconBack = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconFrame : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffIconFrame = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconIconBG : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconIconBG = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconDrop : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconDrop = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconIcon : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconIcon = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public wrapMode TextWrapMode
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconAbilityId : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public wrapMode TextWrapMode
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconAbilityId = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconStack : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public wrapMode TextWrapMode
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconStack = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconCooldown : CooldownControl
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconCooldown = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconName : LabelControl
---@field public font string
---@field public wrapMode TextWrapMode
---@field public verticalAlignment TextAlignment
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconName = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconBarBackdrop : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public level integer
---@field public hidden boolean
---@field public space Space
---@field Edge {file: string, edgeFileWidth: integer, edgeFileHeight: integer, edgeFilePadding: integer}
LUIE_SpellCastBuffIconBarBackdrop = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffIconBar : StatusBarControl
---@field public hidden boolean
---@field public space Space
LUIE_SpellCastBuffIconBar = {}
---------- LVL: 05 ----------
---------- LVL: 06 ----------
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_PlayerBuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerBuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_PlayerDebuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerDebuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_TargetBuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_TargetBuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_TargetDebuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_TargetDebuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_ProminentBuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_ProminentBuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_ProminentDebuffsPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_ProminentDebuffsPreviewAnchorLabelBg = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongPreviewPreviewLabel : LabelControl
---@field public font string
---@field public horizontalAlignment TextAlignment
---@field public verticalAlignment TextAlignment
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
LUIE_SpellCastBuffs_PlayerLongPreviewPreviewLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongPreviewAnchorTexture : TextureControl
---@field public textureFile string
---@field public layer DrawLayer
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerLongPreviewAnchorTexture = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongPreviewAnchorLabel : LabelControl
---@field public font string
---@field public text string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public space Space
---@field Anchor {point: AnchorPosition, relativePoint: AnchorPosition, offsetX: layout_measurement, offsetY: layout_measurement}
---@field Dimensions {x: layout_measurement, y: layout_measurement}
LUIE_SpellCastBuffs_PlayerLongPreviewAnchorLabel = {}
-- ---------------------------------------------------------------------------------------------------------------------
--
---@class LUIE_SpellCastBuffs_PlayerLongPreviewAnchorLabelBg : BackdropControl
---@field public centerColor string
---@field public edgeColor string
---@field public layer DrawLayer
---@field public tier DrawTier
---@field public hidden boolean
---@field public pixelRoundingEnabled boolean
---@field public space Space
---@field AnchorFill boolean
LUIE_SpellCastBuffs_PlayerLongPreviewAnchorLabelBg = {}
---------- LVL: 07 ----------
-- ////// END   : GENERATED FROM C:/Users/dack_janiels/source/repos/LUIE/LuiExtended/LuiExtended/frontend\SpellCastBuffs.xml
