-- -----------------------------------------------------------------------------
-- Catalog EVENT_DISPLAY_ANNOUNCEMENT classification (text match only).
-- Each primary line has its own LUIE string; lookups are built from GetString for localization.
-- -----------------------------------------------------------------------------

--- @class (partial) LUIE.ChatAnnouncements
local ChatAnnouncements = LUIE.ChatAnnouncements

local function AddPrimaryTextLookup(lookup, stringIds, settingsKey)
    for stringIndex = 1, #stringIds do
        lookup[GetString(stringIds[stringIndex])] = settingsKey
    end
end

local CHARACTER_SYSTEM_STRING_IDS =
{
    LUIE_STRING_CA_DISPLAY_ATTRIBUTES_RESET,
    LUIE_STRING_CA_DISPLAY_RIDING_SKILL_INCREASED,
    LUIE_STRING_CA_DISPLAY_BLACKSMITHING_RESEARCH_REDUCED,
    LUIE_STRING_CA_DISPLAY_CLOTHING_RESEARCH_REDUCED,
    LUIE_STRING_CA_DISPLAY_WOODWORKING_RESEARCH_REDUCED,
    LUIE_STRING_CA_DISPLAY_JEWELRY_CRAFT_RESEARCH_REDUCED,
    LUIE_STRING_CA_DISPLAY_ALL_RESEARCH_REDUCED,
    LUIE_STRING_CA_DISPLAY_SKILL_LINE_INCREASE,
    LUIE_STRING_CA_DISPLAY_LEGERDEMAIN_EXPERIENCE_INCREASED,
    LUIE_STRING_CA_DISPLAY_NEW_SIGIL_OF_POWER_SPAWNED,
}

local TRIBUTE_TUTORIAL_STRING_IDS =
{
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_INTRODUCTION,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_GOLD,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_CARDS_AND_ICONOGRAPHY,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_BUYING_CARDS,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_COOLDOWN_PILE,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_ENDING_YOUR_TURN,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_DRAWING_NEW_CARDS,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_OPPONENTS_TURN,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_POWER,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_CURRENCIES_AT_END_OF_TURN,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_COOLDOWN_PILE_TO_DRAW_DECK,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_EMPTY_COOLDOWN_PILE,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_OPPONENTS_SECOND_TURN,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_COMBOS_AND_SYNERGY,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_PRESTIGE_VICTORY,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_PATRON_ICONOGRAPHY,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_PATRON_COSTS,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_PATRON_REWARDS,
    LUIE_STRING_CA_DISPLAY_TRIBUTE_TUTORIAL_PATRON_FAVOR_STATES,
}

local INSTRUMENT_STRING_IDS =
{
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_LUTE_OF_BLUE_LONGING,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_CHIME_OF_THE_ENDLESS,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_TENDERCLAW,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_SHADOW_OF_RAHJIN,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_LILYTONGUE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_SKY_TALKER,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_LONG_FIRE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_HIGHMOURN_DIZI,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_JARSLBANE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_KING_THUNDER,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_JAHAR_FUSOJA,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_PAN_FLUTE_OF_MORACHELLIS,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_REMAN_WAR_DRUM,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_PETRALOOP,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_ATEIAN_FIFE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_SHRIEK_OF_SILK,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_KOTHRINGI_LEVIATHAN_BUGLE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_LODESTONE,
    LUIE_STRING_CA_DISPLAY_INSTRUMENT_DOZZEN_TALHARPA,
}

local INDRIK_STRING_IDS =
{
    LUIE_STRING_CA_DISPLAY_INDRIK_BOONS_REMOVED,
    LUIE_STRING_CA_DISPLAY_INDRIK_WISP_REVEALED,
    LUIE_STRING_CA_DISPLAY_INDRIK_ESCAPED,
    LUIE_STRING_CA_DISPLAY_INDRIK_BOON_DAMAGE,
    LUIE_STRING_CA_DISPLAY_INDRIK_BOON_STEALTH,
    LUIE_STRING_CA_DISPLAY_INDRIK_BOON_HEALTH,
}

local ANTIQUITY_STRING_IDS =
{
    LUIE_STRING_CA_DISPLAY_ANTIQUITY_LEAD_DISCOVERED,
    LUIE_STRING_CA_DISPLAY_ANTIQUITY_CLUE_DISCOVERED,
}

local catalogLookup = {}
AddPrimaryTextLookup(catalogLookup, CHARACTER_SYSTEM_STRING_IDS, "CharacterSystems")
AddPrimaryTextLookup(catalogLookup, TRIBUTE_TUTORIAL_STRING_IDS, "TributeTutorial")
AddPrimaryTextLookup(catalogLookup, INSTRUMENT_STRING_IDS, "InstrumentDisplayed")
AddPrimaryTextLookup(catalogLookup, INDRIK_STRING_IDS, "IndrikEvent")
AddPrimaryTextLookup(catalogLookup, ANTIQUITY_STRING_IDS, "AntiquityDiscovery")

--- @param primaryText string|nil
--- @return CADisplayAnnouncementSection|nil settings
function ChatAnnouncements.ResolveCatalogDisplayAnnouncement(primaryText)
    if not primaryText then
        return nil
    end
    local settingsKey = catalogLookup[primaryText]
    if settingsKey then
        return ChatAnnouncements.SV.DisplayAnnouncements[settingsKey]
    end
end
